### ISSUE TITLE
Will this tool support testing k8s clusters in the future?

### ISSUE THREAD

**Issue by Fredericwu** [krkn-chaos/krkn#175]
Will this tool support testing k8s clusters in the future?
I plan to develop a tool that can support testing K8s clusters based on this tool. Do you have any good suggestions?

thanks

**Comment by chaitanyaenr** [comment]
Hi @Fredericwu, sorry for the delay. We do have plans to fully support testing k8s clusters in the future. We are tracking the efforts in https://github.com/cloud-bulldozer/kraken/issues/185 and https://github.com/cloud-bulldozer/kraken/issues/186. Thanks.

**Comment by chaitanyaenr** [comment]
K8s is fully supported now. Thanks.
