### ISSUE TITLE
Replace openshift client references with kube client

### ISSUE THREAD

**Issue by chaitanyaenr** [krkn-chaos/krkn#185]
There are currently two areas that can be improved:
- While we are using the kubernetes python client in most of the code base, we still have a couple of places where we use the kubectl and oc clients which we need to replace wherever possible to avoid the need for having them installed on the host in case of using standlone way of running kraken ( python ) vs containers where this shouldn't be an issue given that we package the clients into the image.
- There are a couple of references of oc cli calls which can be replaced with kubectl. In case where an operation is specific to OpenShift, we need to make sure to use the distribution mentioned in the config to avoid running them in case of running kraken on kubernetes -  https://github.com/cloud-bulldozer/kraken/blob/master/config/config.yaml#L2 to avoid bombing out.

**Comment by sanjacodes** [comment]
Let's try and replace all instances of oc and kubectl by using the [Kubernetes Python Client](https://github.com/kubernetes-client/python) wherever possible.

**Comment by chaitanyaenr** [comment]
Fixed in the recent releases. Thanks.
